### ISSUE TITLE
Document the process of configuring Pelorus to pull metrics from openshift prometheus

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#194]
1. Get the password for prometheus: `oc get secret grafana-datasources -n openshift-monitoring -o jsonpath='{.data.prometheus\.yaml}' | base64 -d`
2. Add to values file:
```
extra_prometheus_hosts:
- id: "openshift-monitoring"
  hostname: "prometheus-k8s.openshift-monitoring.svc:9091"
  password: "<redacted>"
```

We also need to open a PR to make some helm changes to the additional script configs to target specific metrics.
