### ISSUE TITLE
committime exporter doesn't work with binary builds

### ISSUE THREAD

**Issue by jlozano-rh** [konveyor/pelorus#317]
In Red Hat we have customers that have all it's builds configured with Binary builds, that are similar to next:
```yaml
source:
    type: Binary
strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12'
      dockerfilePath: openshift/Dockerfile
```

But the committime exporter is trying to find the next properties in builds triggered `.spec.source.git.uri` and `.spec.revision.git.commit`. These properties do not exist because the build is binary, so the committime exporter pod is recording the following log:

```log
10-21-2021 17:26:14 WARNING  Build example-project/example-build-13 in app example-app is missing required attributes to collect data. Skipping.
10-21-2021 17:26:14 DEBUG    'NoneType' object has no attribute 'git'
Traceback (most recent call last):
  File "/opt/app-root/src/committime/collector_base.py", line 185, in get_metric_from_build
    commit_sha = build.spec.revision.git.commit
AttributeError: 'NoneType' object has no attribute 'git'
10-21-2021 17:26:14 DEBUG    Searching for builds with label: pelorus/app.name in namespace: example-project
10-21-2021 17:26:14 DEBUG    Repo URL for app example-app is currently None
10-21-2021 17:26:14 DEBUG    http://gitlab.company.com/example/app.git
10-21-2021 17:26:14 DEBUG    http://gitlab.company.com/example/app.git
10-21-2021 17:26:14 WARNING  Build example-project/example-app-2 in app example-app is missing required attributes to collect data. Skipping.
10-21-2021 17:26:14 DEBUG    'NoneType' object has no attribute 'imageDigest'
```

It would be a good idea to propose that the committime exporter code implement a way of doing things for binary builds.
