### ISSUE TITLE
Support for other image references in deploytime exporter

### ISSUE THREAD

**Issue by jlozano-rh** [konveyor/pelorus#330]
Deploying an app with tekton pipeline and another registry... the resulting pod has not the correct SHA in its place. I mean, the correct way is:
```yaml
spec:
  containers:
    - name: appname
       image: >-
         image-registry.openshift-image-registry.svc:5000/project/appname@sha256:afg1zk03979456a9023eff2587652d30
```

But, In my case, when use quay as registry for my docker images, the same snippet is slightly different:
```yaml
spec:
  containers:
    - name: appname
       image: >-
         quay-registry.project.cluster-url.com/organization/appname:latest
```

It does not have a SHA in the image URL. So my proposal is to take the image SHA from somewhere else. For example:
```yaml
status:
  containerStatuses:
    - name: retail-queloque
       imageID: >-
         quay-registry.project.cluster-url.com/organization/appname@sha256:afg1zk03979456a9023eff932587652d30
```

For the deploytime exporter works well, I had to change the line number 132 for this one:
```python
images = (sha for s in pod.status.containerStatuses if (sha := image_sha(s.imageID)))
```

This worked for me.
