### ISSUE TITLE
Deploytime exporters template metadata for app.kub.io/name should fall back to deploymentConfig meta if empty

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#434]
e.g.
```
template:
        metadata:
          creationTimestamp:
          labels:
            e2e-app: "true"
            app: todolist
            application: todolist
            deploymentconfig: todolist-mongo-go
            app.kubernetes.io/name: todolist
```
template.metadata.labels: app.kubernetes.io/name:  IF EMPTY...
use: deploymentConfig.metadata.labels
```
kind: DeploymentConfig
    metadata:
      name: todolist
      namespace: mongo-persistent
      labels:
        app: todolist
        app.kubernetes.io/name: todolist
```
