### ISSUE TITLE
Support Bitbucket API 1.0 in committime exporter

### ISSUE THREAD

**Issue by xacobecm** [konveyor/pelorus#678]
On premise instances of bitbucket (Bitbucket Server) do not support API 2.0, as it is only available for Bitbucket Cloud. Can we get a committime exporter collector for Bitbucket Server?

**Comment by xacobecm** [comment]
First of all thank you for your quick response to this issue. I have tested your PR and I found a little problem, but I'm not sure if it's on my side. Let me detail what I did:

As the network traffic from the organization's OpenShift cluster to GitHub is restricted, I could not mount this PR as documented in https://pelorus.readthedocs.io/en/latest/Configuration/
```yaml
exporters:
  instances:
  - app_name: committime-github
    exporter_type: comittime
    source_url: https://github.com/konveyor/pelorus.git
    source_ref: refs/pull/680/head
    env_from_secrets:
    - github-credentials
    env_from_configmaps:
    - pelorus-config
    - committime-config
```

What I did instead is create a configmap with the new `collector_bitbucket.py` and mounted it as a volume in `/opt/app-root/lib64/python3.9/site-packages/committime/collector_bitbucket.py`. This produced the following error: `ModuleNotFoundError: No module named 'pelorus.timeutil'`.

I found the file on the repo so I deleted the import and pasted the methods directly in `collector_bitbucket.py` (definitely not a good fix but it's the first thing that came to my mind) . After this, I started to read debug logs retrieving commit information, so I assume it works. 

Therefore I can confirm the code works, but I can't verify that the module `pelorus.timeutil` can be imported.
