### ISSUE TITLE
Helm values in the openAPIV3Schema

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#751]
We have problem when we want to use properties section in here. The OCP evaluates every entry in properties and it's not matching openAPIV3Schema because it's Helm values.yaml which is in fact json.

I have tried with:
```
              properties:
                exporters:
                  description: >-
                    References configuration for the Pelorus exporters. More
                    info about exporters configuration:
                    https://pelorus.readthedocs.io/en/latest/Configuration/#configuring-exporters-details
                  type: object
                  properties:
                    instances:
                      description: >-
                        Exporter instances configuration. More information:
                        https://pelorus.readthedocs.io/en/latest/Configuration/
                      type: array
                      items:
                        type: object
                      properties:
                        app_name:
                          description: 'Exporter name, must start with "- ".'
                          type: string
                        enabled:
                          description: 'If set to false, exporter won''t be provisioned.'
                          type: boolean
                        env_from_configmaps:
                          description: >-
                            ConfigMap name(s) with configuration used by the
                            exporter instance.
                          type: object
                        env_from_secrets:
                          description: >-
                            Secret name(s) with secrets used by the exporter
                            instance.
                          type: object
                        exporter_type:
                          description: >-
                            Exporter type as in the:
                            https://pelorus.readthedocs.io/en/latest/Configuration/#configuring-exporters-overview
                          type: string
```

But OCP was creating malformed values, because there is no such type that can fit our list (problematic - at the beginning of the line):
```
- app_name: first
- app_name: second
```

_Originally posted by @mpryc in https://github.com/konveyor/pelorus/pull/750#discussion_r1050746324_

**Comment by KevinMGranger** [comment]
I don't understand the issue-- the form can't represent this spec, or we can't represent what we want in the spec?

**Comment by mpryc** [comment]
> I don't understand the issue-- the form can't represent this spec, or we can't represent what we want in the spec?

The form can not represent this spec (with "-")

**Comment by KevinMGranger** [comment]
I still don't understand. Where are dashes coming from, and why does `app_name` say they're required? Are you saying the form doesn't understand how to do values nested in an array like we need in `instances`?

**Comment by mpryc** [comment]
> 

The example OpenShift instance spec is as follows. You can see the "-" before app_name. This is exactly the same as we have in our documentation (many of the code-snippets in our documentation have such examples): https://pelorus.readthedocs.io/en/latest/Configuration/#instance-config

This *works*, but not when we want to add specific type to the charts.pelorus.konveyor.io/v1alpha1 schema under instances. The supported values that can define what is the value type is within:

`supported values: "array", "boolean", "integer", "number", "object", "string"" for field "spec.validation.openAPIV3Schema`

Ideally we would like to have an array of objects, but this won't work as array of object is defined by indentation and not the "-" list.


```
kind: Pelorus
apiVersion: charts.pelorus.konveyor.io/v1alpha1
metadata:
  name: pelorus-sample
  namespace: pelorus
spec:
  exporters:
    global: {}
    instances:
      - app_name: deploytime-exporter
        exporter_type: deploytime
      - app_name: failuretime-exporter
        enabled: false
        env_from_configmaps:
          - pelorus-config
          - failuretime-config
        env_from_secrets:
          - jira-secret
        exporter_type: failure
      - app_name: committime-exporter
        exporter_type: committime
  extra_prometheus_hosts: null
  openshift_prometheus_basic_auth_pass: changeme
  openshift_prometheus_htpasswd_auth: 'internal:{SHA}+pvrmeQCmtWmYVOZ57uuITVghrM='
  prometheus_retention: 1y
  prometheus_retention_size: 1GB
  prometheus_storage: false
  prometheus_storage_pvc_capacity: 2Gi
  prometheus_storage_pvc_storageclass: gp2
```

I hope this clarifies what the problem is?

**Comment by KevinMGranger** [comment]
I still don't understand. The following are both the same:

```yaml
instances:
- app_name: deploytime-exporter
  exporter_type: deploytime
```

```yaml
instances:
  - app_name: deploytime-exporter
    exporter_type: deploytime
```

```python
import yaml

without_indentation = yaml.load("""
instances:
- app_name: deploytime-exporter
  exporter_type: deploytime
""", yaml.Loader)

with_indentation = yaml.load("""
instances:
  - app_name: deploytime-exporter
    exporter_type: deploytime
""", yaml.Loader)

assert without_indentation == with_indentation
```

**Comment by mpryc** [comment]
> I still don't understand. The following are both the same:

It's not the Helm that has problems. It's an OpenShift validation of the openAPIV3Schema that has issues with the values. OpenShift does not recognize object type if it starts with dash "-". Attached is an example of such error:
![Screenshot from 2022-12-20 22-51-33](https://user-images.githubusercontent.com/16115240/208774012-c65b787c-b1b4-4288-bd2c-9726de43cbe3.png)


If you still have concerns I will go through an example offline Tomorrow so you can see.

**Comment by mpryc** [comment]
As @KevinMGranger showed offline entire problem is with the indentation of the properties under instances. Correct one should be:

```
                      items:
                        type: object
                      properties:

# Change to:

                      items:
                        type: object
                        properties:
```

So:

```
              properties:
                exporters:
                  description: >-
                    References configuration for the Pelorus exporters. More
                    info about exporters configuration:
                    https://pelorus.readthedocs.io/en/latest/Configuration/#configuring-exporters-details
                  type: object
                  properties:
                    instances:
                      description: >-
                        Exporter instances configuration. More information:
                        https://pelorus.readthedocs.io/en/latest/Configuration/
                      type: array
                      items:
                        type: object
                        properties:
                          app_name:
                            description: 'Exporter name, must start with "- ".'
                            type: string
                          enabled:
                            description: 'If set to false, exporter won''t be provisioned.'
                            type: boolean
                          env_from_configmaps:
                            description: >-
                              ConfigMap name(s) with configuration used by the
                              exporter instance.
                            type: object
                          env_from_secrets:
                            description: >-
                              Secret name(s) with secrets used by the exporter
                              instance.
                            type: object
                          exporter_type:
                            description: >-
                              Exporter type as in the:
                              https://pelorus.readthedocs.io/en/latest/Configuration/#configuring-exporters-overview
                            type: string
```
