### ISSUE TITLE
Bring Webhook POC to production

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#846]
https://github.com/konveyor/pelorus/pull/836

* Features:
  - [ ]   plugable webhook
  - [ ]   validation of push payload 
  - [ ]  exporting data to prometheus 
  - [ ]  pelorus handler plugin
    - [ ]  committime
    - [ ]  deploytime
    - [ ]  failure
    - [ ]  github handler??
       - [ ]  ssl connection
        - [ ]  generic way to secure the payload

* Requirements:
  *  SSL 
  *  Encryption
  * unit tests
  * 1 integration test ( prow e2e )
  * Doc
    *  Developer doc
    *  User doc
  * Include the same push event found in e2e into the tekton demo workflow

* Announcement to interested parties
* Architecture doc ( draft )
   * https://github.com/konveyor/pelorus/pull/844

Notes:
* 

Progress:

**Comment by weshayutin** [comment]
https://github.com/konveyor/pelorus/pull/844

**Comment by mpryc** [comment]
It is possible to deploy exporter using the `latest` tag already, need to package and document it. 


```yaml
exporters:
  instances:
  - app_name: deploytime-exporter
    exporter_type: deploytime

  - app_name: webhook-exporter
    exporter_type: webhook
    image_tag: latest
```

The route to deployed webhook:
```shell
$ oc get routes -n pelorus webhook-exporter
```

Use the webhook url to sent data to from the route with suffix `/pelorus/webhook`, e.g. to use data from `exporters/tests/data` folder:


`$ curl -X POST http://`**<webhook_url>**`/ -d @./webhook_pelorus_committime.json -H "Content-Type: application/json" -H "User-Agent: Pelorus-Webhook/test" -H "X-Pelorus-Event: committime"`
