### ISSUE TITLE
Pelorus Operator v0.0.3 is broken on the RBAC permissions.

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#849]
Pelorus Operator version 0.0.3 available in the OpenShift community marketplace is broken. It do installs fine, but while trying to create pelorus instance it gives error:

```
        failed to install release: rendered manifests contain a resource that
        already exists. Unable to continue with install: could not get
        information about the resource ClusterRoleBinding "pelorus-grafana" in
        namespace "": clusterrolebindings.rbac.authorization.k8s.io
        "pelorus-grafana" is forbidden: User
        "system:serviceaccount:pelorus:pelorus-operator-controller-manager"
        cannot get resource "clusterrolebindings" in API group
        "rbac.authorization.k8s.io" at the cluster scope
```

This is due to the wrong RBAC that are within CSV for Pelorus project. They were created using operator-sdk, but looks like very different RBAC are when creating with operator-sdk that has access to the OCP cluster (via export KUBECONFIG or oc login) or without.

The difference between rules:
Without being logged, we have additional fields (ignoring all the rest fields, as the file is pretty long and does not have same order of rbac privs):
```
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
```

With being logged, we have additional fields (ignoring all the rest fields, as the file is pretty long and does not have same order of rbac privs):
```
      clusterPermissions:
      - rules:
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - '*'
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - '*'
        - apiGroups:
          - integreatly.org
          resources:
          - grafanadashboards
          - grafanadatasources
          - grafanas
          verbs:
          - '*'
        - apiGroups:
          - image.openshift.io
          resources:
          - imagestreams
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheuses
          - prometheusrules
          - servicemonitors
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          - serviceaccounts
          - services
          verbs:
          - '*'
```
