### ISSUE TITLE
mysql app & related deploytime metrics not visible in grafana dashboard

### ISSUE THREAD

**Issue by stillalearner** [konveyor/pelorus#897]
**Description:**

Tried creating a mysql deployment using oc new-app in a new namespace named mysql, and enabled the deploytime exporter but the app is not visible in the grafana dashboard.

**Environment used:**

OCP 4.12

**How to reproduce?**

1. Create a new namespace mysql and deploy  mysql app:
 oc new-app --image-stream=mysql:latest -n mysql

2. Installing pelorus operator 0.0.5 and creating a pelorus instance with below spec:
```yaml
spec:
  exporters:
    instances:
    - app_name: dep-exporter122
      enabled: true
      exporter_type: deploytime
      extraEnv:
      - name: LOG_LEVEL
        value: DEBUG
      - name: NAMESPACES
        value: mysql
```        
3. Login to the grafana dashboard and check the application list in Software Delivery Performance - By App Dashboard.

**Expected results:**

mysql app should be visible in grafana

**Actual results:**

mysql app is not visible in grafana.

**Additional info:**

Initially after deploying the mysql app, only the deployment has the label **app.kubernetes.io/name: mysql**
and the deploytime metrics was not showing the data about mysql app.

On adding the same label to ReplicaSet & the mysql Pod manually, the deploytime metrics started showing the data:
```
# HELP deploy_timestamp Deployment timestamp
# TYPE deploy_timestamp gauge
deploy_timestamp{app="mysql",image_sha="sha256:e2c4296aa3854c474a1cf1131f2f43cd19a1340bef510c180261a175bd58d58d",namespace="mysql"} 1.679042096e+09 1679042096000
# HELP deployment_active Active deployments in cluster
# TYPE deployment_active gauge
deployment_active{app="mysql",image_sha="sha256:e2c4296aa3854c474a1cf1131f2f43cd19a1340bef510c180261a175bd58d58d",namespace="mysql"} 1.679042096e+09
```
But the app still not visible in the grafana.
